services:

    golang:
        image: $REGISTRY/$NAME:$VERSION
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - REGISTRY
                - GOLANG_SOURCE
                - GOLANG_VERSION
            tags:
                - $REGISTRY/$NAME:latest
                - $SYNC_TARGET/$NAME:$VERSION
                - $SYNC_TARGET/$NAME:latest
