
version: 3

dotenv: [ '.env' ]

tasks:

    build-golang:
        silent: true
        internal: true
        vars:
            GOLANG_VERSION:
                sh: lynx -dump -listonly {{.GOLANG_URL}} | awk '{print $2}' | grep 'go'{{.VERSION}} | grep 'linux-'{{.GOLANG_ARCH}} | sed -r 's,.*/go('$1'.*).linux.*,\1,g' | sort -V | tail -n1
            GOLANG_SOURCE:
                sh: lynx -dump -listonly {{.GOLANG_URL}} | awk '{print $2}' | grep 'go'{{.GOLANG_VERSION}} | grep 'linux-'{{.GOLANG_ARCH}}'.tar.gz' | head -n1
        cmds:
            - echo "- {{.TITLE}}"
            - sed -i '/VERSION=/d; /SOURCE=/d;' .env
            - echo -e "GOLANG_VERSION={{.GOLANG_VERSION}}\nGOLANG_SOURCE={{.GOLANG_SOURCE}}\nVERSION={{.VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/VERSION=/d; /SOURCE=/d;' .env
            - echo "[ Done ]"

    build:
        desc: 'Build Go Programming Language'
        silent: true
        cmds:
            - echo -e '\e[44;1m[ Building Go Programming Language ]\e[0;0m'
            - for: { var: GOLANG_VERSION_LIST }
              task: build-golang
              vars:
                TITLE: 'Golang {{.ITEM}}'
                VERSION: '{{.ITEM}}'

    sync-golang:
        silent: true
        internal: true
        vars:
            GOLANG_VERSION:
                sh: lynx -dump -listonly {{.GOLANG_URL}} | awk '{print $2}' | grep 'go'{{.VERSION}} | grep 'linux-'{{.GOLANG_ARCH}} | sed -r 's,.*/go('$1'.*).linux.*,\1,g' | sort -V | tail -n1
        cmds:
            - echo "Sync {{.REGISTRY}}/{{.NAME}}:{{.VERSION}} => {{.SYNC_TARGET}}/{{.NAME}}:{{.VERSION}}"
            - skopeo copy docker://{{.REGISTRY}}/{{.NAME}}:{{.VERSION}} docker://{{.SYNC_TARGET}}/{{.NAME}}:{{.VERSION}}
            - echo "Sync {{.REGISTRY}}/{{.NAME}}:latest => {{.SYNC_TARGET}}/{{.NAME}}:latest"
            - skopeo copy docker://{{.REGISTRY}}/{{.NAME}}:latest docker://{{.SYNC_TARGET}}/{{.NAME}}:latest
            - echo "[ Done ]"

    sync:
        desc: 'Synchronize with DockerHub'
        silent: true
        cmds:
            - echo -e '\e[44;1m[ Synchronize with DockerHub ]\e[0;0m'
            - for: { var: GOLANG_VERSION_LIST }
              task: sync-golang
              vars:
                VERSION: '{{.ITEM}}'


    checkout-go:
        silent: true
        internal: true
        vars:
            TAG:
                sh: lynx -dump -listonly {{.GOLANG_URL}} | awk '{print $2}' | grep 'go'{{.VERSION}} | grep 'linux-'{{.GOLANG_ARCH}} | sed -r 's,.*/go('$1'.*).linux.*,\1,g' | sort -V | tail -n1
        cmds:
            - echo -n "{{.TAG}} "

    checkout:
        silent: true
        cmds:
            - for: { var: GOLANG_VERSION_LIST }
              task: checkout-go
              vars:
                VERSION: '{{.ITEM}}'

    all:
        desc: 'Build and Synchronize'
        silent: true
        cmds:
            - task: build
            - task: sync

    default:
        silent: true
        cmds:
            - task -l
