
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Caddy Web Server'
        silent: true
        vars:
            CADDY_VERSION:
                sh: git ls-remote --tags {{.CADDY_SOURCE}} | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -Ev 'beta|rc' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo -e '\e[44;1m[ Building Caddy Web Server ]\e[0;0m'
            - sed -i '/CADDY_VERSION=/d' .env
            - echo "CADDY_VERSION={{.CADDY_VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/CADDY_VERSION=/d' .env
            - echo "[ Done ]"

    checkout:
        silent: true
        vars:
            CADDY_VERSION:
                sh: git ls-remote --tags {{.CADDY_SOURCE}} | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -Ev 'beta|rc' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo {{.CADDY_VERSION}}

    default:
        silent: true
        cmds:
            - task -l
