
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Element Web'
        silent: true
        vars:
            ELEMENT_VERSION:
                sh: git ls-remote --refs {{.ELEMENT_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo -e '\e[44;1m[ Building Element Web ]\e[0;0m'
            - sed -i '/ELEMENT_VERSION=/d' .env
            - echo "ELEMENT_VERSION={{.ELEMENT_VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/ELEMENT_VERSION=/d' .env
            - echo "[ Done ]"

    checkout:
        silent: true
        vars:
            ELEMENT_VERSION:
                sh: git ls-remote --refs {{.ELEMENT_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo {{.ELEMENT_VERSION}}

    default:
        silent: true
        cmds:
            - task -l
