services:

    dendrite:
        image: $REGISTRY/$NAME:$DENDRITE_VERSION
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - REGISTRY
                - DENDRITE_SOURCE
                - DENDRITE_VERSION
                - PUID
                - PGID
            tags:
                - $REGISTRY/$NAME:latest
                - $SYNC_TARGET/$NAME:$DENDRITE_VERSION
                - $SYNC_TARGET/$NAME:latest
