
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Matrix Dendrite Server'
        silent: true
        vars:
            DENDRITE_VERSION:
                sh: git ls-remote --refs {{.DENDRITE_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo -e '\e[44;1m[ Building Matrix Dendrite Server ]\e[0;0m'
            - sed -i '/DENDRITE_VERSION=/d' .env
            - echo "DENDRITE_VERSION={{.DENDRITE_VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/DENDRITE_VERSION=/d' .env
            - echo "[ Done ]"

    sync:
        desc: "Synchronize with DockerHub"
        silent: true
        vars:
            DENDRITE_VERSION:
                sh: git ls-remote --refs {{.DENDRITE_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo -e '\e[44;1m[ Synchronize with DockerHub ]\e[0;0m'
            - echo "Sync {{.REGISTRY}}/{{.NAME}}:{{.DENDRITE_VERSION}} => {{.SYNC_TARGET}}/{{.NAME}}:{{.DENDRITE_VERSION}}"
            - skopeo copy docker://{{.REGISTRY}}/{{.NAME}}:{{.DENDRITE_VERSION}} docker://{{.SYNC_TARGET}}/{{.NAME}}:{{.DENDRITE_VERSION}}
            - echo "Sync {{.REGISTRY}}/{{.NAME}}:latest => {{.SYNC_TARGET}}/{{.NAME}}:latest"
            - skopeo copy docker://{{.REGISTRY}}/{{.NAME}}:latest docker://{{.SYNC_TARGET}}/{{.NAME}}:latest
            - echo "[ Done ]"

    checkout:
        silent: true
        vars:
            DENDRITE_VERSION:
                sh: git ls-remote --refs {{.DENDRITE_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo {{.DENDRITE_VERSION}}

    all:
        desc: 'Build and Synchronize'
        silent: true
        cmds:
            - task: build
            - task: sync

    default:
        silent: true
        cmds:
            - task -l
