
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Matrix Dendrite Server'
        silent: true
        vars:
            DENDRITE_VERSION:
                sh: git ls-remote --refs {{.DENDRITE_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo -e '\e[44;1m[ Building Matrix Dendrite Server ]\e[0;0m'
            - sed -i '/DENDRITE_VERSION=/d' .env
            - echo "DENDRITE_VERSION={{.DENDRITE_VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/DENDRITE_VERSION=/d' .env
            - echo "[ Done ]"

    checkout:
        silent: true
        vars:
            DENDRITE_VERSION:
                sh: git ls-remote --refs {{.DENDRITE_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo {{.DENDRITE_VERSION}}

    default:
        silent: true
        cmds:
            - task -l
