services:

    gitea-runner:
        image: $REGISTRY/$NAME:$RUNNER_VERSION
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - REGISTRY
                - PUID
                - PGID
                - RUNNER_DATA
                - RUNNER_SOURCE
                - RUNNER_VERSION
            tags:
                - $REGISTRY/$NAME:latest
                - $SYNC_TARGET/$NAME:$RUNNER_VERSION
                - $SYNC_TARGET/$NAME:latest
