
version: 3

dotenv: [ '.env' ]

tasks:

    build-bind9:
        silent: true
        internal: true
        vars:
            BIND9_VERSION:
                sh: git ls-remote --refs {{.BIND9_SOURCE}} "refs/tags/v{{.VERSION}}.*" 2>/dev/null | sed 's,.*\/,,; s,\^{},,;' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo "- {{.TITLE}}"
            - sed -i '/VERSION=/d' .env
            - echo -e "BIND9_VERSION={{.BIND9_VERSION}}\nVERSION={{.VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/VERSION=/d' .env
            - echo "[ Done ]"

    build:
        desc: 'Build Bind9 DNS Server'
        silent: true
        cmds:
            - echo -e '\e[44;1m[ Building Bind9 DNS Server ]\e[0;0m'
            - for: { var: BIND9_VERSION_LIST }
              task: build-bind9
              vars:
                TITLE: 'Bind9 {{.ITEM}}'
                VERSION: '{{.ITEM}}'

    checkout-bind9:
        silent: true
        internal: true
        vars:
            BIND9_VERSION:
                sh: git ls-remote --refs {{.BIND9_SOURCE}} "refs/tags/v{{.VERSION}}.*" 2>/dev/null | sed 's,.*\/,,; s,\^{},,;' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo -n "{{.BIND9_VERSION}} "

    checkout:
        silent: true
        cmds:
            - for: { var: BIND9_VERSION_LIST }
              task: checkout-bind9
              vars:
                VERSION: '{{.ITEM}}'

    default:
        silent: true
        cmds:
            - task -l
