
version: 3

dotenv: [ '.env' ]

tasks:

    build-bind9:
        silent: true
        internal: true
        vars:
            BIND9_VERSION:
                sh: git ls-remote --refs {{.BIND9_SOURCE}} "refs/tags/v{{.VERSION}}.*" 2>/dev/null | sed 's,.*\/,,; s,\^{},,;' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo "- {{.TITLE}}"
            - sed -i '/VERSION=/d' .env
            - echo -e "BIND9_VERSION={{.BIND9_VERSION}}\nVERSION={{.VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/VERSION=/d' .env
            - echo "[ Done ]"

    build:
        desc: 'Build Bind9 DNS Server'
        silent: true
        cmds:
            - echo -e '\e[44;1m[ Building Bind9 DNS Server ]\e[0;0m'
            - for: { var: BIND9_VERSION_LIST }
              task: build-bind9
              vars:
                TITLE: 'Bind9 {{.ITEM}}'
                VERSION: '{{.ITEM}}'

    sync-bind9:
        silent: true
        internal: true
        vars:
            BIND9_VERSION:
                sh: git ls-remote --refs {{.BIND9_SOURCE}} "refs/tags/v{{.VERSION}}.*" 2>/dev/null | sed 's,.*\/,,; s,\^{},,;' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo "Sync {{.REGISTRY}}/{{.NAME}}:{{.BIND9_VERSION}} => {{.SYNC_TARGET}}/{{.NAME}}:{{.BIND9_VERSION}}"
            - skopeo copy docker://{{.REGISTRY}}/{{.NAME}}:{{.BIND9_VERSION}} docker://{{.SYNC_TARGET}}/{{.NAME}}:{{.BIND9_VERSION}}
            - echo "Sync {{.REGISTRY}}/{{.NAME}}:{{.VERSION}} => {{.SYNC_TARGET}}/{{.NAME}}:{{.VERSION}}"
            - skopeo copy docker://{{.REGISTRY}}/{{.NAME}}:{{.VERSION}} docker://{{.SYNC_TARGET}}/{{.NAME}}:{{.VERSION}}
            - echo "Sync {{.REGISTRY}}/{{.NAME}}:latest => {{.SYNC_TARGET}}/{{.NAME}}:latest"
            - skopeo copy docker://{{.REGISTRY}}/{{.NAME}}:latest docker://{{.SYNC_TARGET}}/{{.NAME}}:latest
            - echo "[ Done ]"

    sync:
        desc: 'Synchronize with DockerHub'
        silent: true
        cmds:
            - echo -e '\e[44;1m[ Synchronize with DockerHub ]\e[0;0m'
            - for: { var: BIND9_VERSION_LIST }
              task: sync-bind9
              vars:
                VERSION: '{{.ITEM}}'

    checkout-bind9:
        silent: true
        internal: true
        vars:
            BIND9_VERSION:
                sh: git ls-remote --refs {{.BIND9_SOURCE}} "refs/tags/v{{.VERSION}}.*" 2>/dev/null | sed 's,.*\/,,; s,\^{},,;' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo -n "{{.BIND9_VERSION}} "

    checkout:
        silent: true
        cmds:
            - for: { var: BIND9_VERSION_LIST }
              task: checkout-bind9
              vars:
                VERSION: '{{.ITEM}}'

    all:
        desc: 'Build and Synchronize'
        silent: true
        cmds:
            - task: build
            - task: sync

    default:
        silent: true
        cmds:
            - task -l
