services:

    onedrive:
        image: $REGISTRY/$NAME:$PROMETHEUS_VERSION
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - REGISTRY
                - PUID
                - PGID
                - PROMETHEUS_SOURCE
                - PROMETHEUS_VERSION
            tags:
                - $REGISTRY/$NAME:latest
                - $SYNC_TARGET/$NAME:$PROMETHEUS_VERSION
                - $SYNC_TARGET/$NAME:latest
