
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Gitea Server'
        silent: true
        vars:
            GITEA_VERSION:
                sh: git ls-remote --tags {{.GITEA_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | grep -v 'dev' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo -e '\e[44;1m[ Building Gitea Server ]\e[0;0m'
            - sed -i '/GITEA_VERSION=/d' .env
            - echo "GITEA_VERSION={{.GITEA_VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/GITEA_VERSION=/d' .env
            - echo "[ Done ]"

    checkout:
        silent: true
        vars:
            GITEA_VERSION:
                sh: git ls-remote --tags {{.GITEA_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | grep -v 'dev' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo {{.GITEA_VERSION}}

    default:
        silent: true
        cmds:
            - task -l
