
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Gitea Server'
        silent: true
        vars:
            GITEA_VERSION:
                sh: git ls-remote --tags {{.GITEA_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | grep -v 'dev' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo -e '\e[44;1m[ Building Gitea Server ]\e[0;0m'
            - sed -i '/GITEA_VERSION=/d' .env
            - echo "GITEA_VERSION={{.GITEA_VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/GITEA_VERSION=/d' .env
            - echo "[ Done ]"

    sync:
        desc: "Synchronize with DockerHub"
        silent: true
        vars:
            GITEA_VERSION:
                sh: git ls-remote --tags {{.GITEA_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | grep -v 'dev' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo -e '\e[44;1m[ Synchronize with DockerHub ]\e[0;0m'
            - echo "Sync {{.REGISTRY}}/{{.NAME}}:{{.GITEA_VERSION}} => {{.SYNC_TARGET}}/{{.NAME}}:{{.GITEA_VERSION}}"
            - skopeo copy docker://{{.REGISTRY}}/{{.NAME}}:{{.GITEA_VERSION}} docker://{{.SYNC_TARGET}}/{{.NAME}}:{{.GITEA_VERSION}}
            - echo "Sync {{.REGISTRY}}/{{.NAME}}:latest => {{.SYNC_TARGET}}/{{.NAME}}:latest"
            - skopeo copy docker://{{.REGISTRY}}/{{.NAME}}:latest docker://{{.SYNC_TARGET}}/{{.NAME}}:latest
            - echo "[ Done ]"

    checkout:
        silent: true
        vars:
            GITEA_VERSION:
                sh: git ls-remote --tags {{.GITEA_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | grep -v 'dev' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo {{.GITEA_VERSION}}

    all:
        desc: 'Build and Synchronize'
        silent: true
        cmds:
            - task: build
            - task: sync

    default:
        silent: true
        cmds:
            - task -l
