services:

    caddy:
        image: $REGISTRY/$NAME:$KEYCLOAK_VERSION
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - REGISTRY
                - KEYCLOAK_SOURCE
                - KEYCLOAK_VERSION
                - JDK_VERSION
                - PUID
                - PGID
            tags:
                - $REGISTRY/$NAME:latest
                - $SYNC_TARGET/$NAME:$KEYCLOAK_VERSION
                - $SYNC_TARGET/$NAME:latest
