
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Keycloak'
        silent: true
        vars:
            KEYCLOAK_VERSION:
                sh: git ls-remote --refs {{.KEYCLOAK_SOURCE}} 'refs/tags/*' | sed -e '/.*^{}/d; s,.*\/,,; /[a-zA-Z]/d' | sort --version-sort | tail -n1
        cmds:
            - echo -e '\e[44;1m[ Building Keycloak ]\e[0;0m'
            - sed -i '/KEYCLOAK_VERSION=/d' .env
            - echo "KEYCLOAK_VERSION={{.KEYCLOAK_VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/KEYCLOAK_VERSION=/d' .env
            - echo "[ Done ]"

    checkout:
        silent: true
        vars:
            KEYCLOAK_VERSION:
                sh: git ls-remote --refs {{.KEYCLOAK_SOURCE}} 'refs/tags/*' | sed -e '/.*^{}/d; s,.*\/,,; /[a-zA-Z]/d' | sort --version-sort | tail -n1
        cmds:
            - echo {{.KEYCLOAK_VERSION}}

    all:
        desc: 'Build and Synchronize'
        silent: true
        cmds:
            - task: build

    default:
        silent: true
        cmds:
            - task -l
