
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Grafana'
        silent: true
        vars:
            GRAFANA_VERSION:
                sh: git ls-remote --tags https://github.com/grafana/grafana 'refs/tags/v*' | sed 's,.*\/,,; s,\^{},,;' | grep -E 'v[0-9.]+$' | sort --version-sort --uniq | tail -n1 | sed 's/v//'
        cmds:
            - echo -e '\e[44;1m[ Building Grafana ]\e[0;0m'
            - sed -i '/GRAFANA_VERSION=/d' .env
            - echo "GRAFANA_VERSION={{.GRAFANA_VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/GRAFANA_VERSION=/d' .env
            - echo "[ Done ]"

    checkout:
        silent: true
        vars:
            GRAFANA_VERSION:
                sh: git ls-remote --tags https://github.com/grafana/grafana 'refs/tags/v*' | sed 's,.*\/,,; s,\^{},,;' | grep -E 'v[0-9.]+$' | sort --version-sort --uniq | tail -n1 | sed 's/v//'
        cmds:
            - echo {{.GRAFANA_VERSION}}

    default:
        silent: true
        cmds:
            - task -l
