services:

    unit:
        image: $REGISTRY/$NAME:$NXT_VERSION
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - REGISTRY
                - PUID
                - PGID
                - UNIT_SOURCE
                - UNIT_VERSION
                - NJS_SOURCE
                - NJS_VERSION
            tags:
                - $REGISTRY/$NAME:latest
