services:

    machine-learning:
        image: $REGISTRY/$NAME-machine-learning:$IMMICH_VERSION
        env_file: .env
        build:
            context: immich/machine-learning
            dockerfile: ../../Dockerfile.machine-learning
            tags:
                - $REGISTRY/$NAME-machine-learning:latest
                - $SYNC_TARGET/$NAME-machine-learning:latest
                - $SYNC_TARGET/$NAME-machine-learning:$IMMICH_VERSION

    server:
        image: $REGISTRY/$NAME-server:$IMMICH_VERSION
        env_file: .env
        build:
            context: immich
            dockerfile: ../Dockerfile.server
            tags:
                - $REGISTRY/$NAME-server:latest
                - $SYNC_TARGET/$NAME-server:latest
                - $SYNC_TARGET/$NAME-server:$IMMICH_VERSION
