
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Immich Server'
        silent: true
        vars:
#            IMMICH_VERSION:
#                sh: git ls-remote --tags {{.IMMICH_SOURCE}} 'refs/tags/*' 2>/dev/null | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -E '^v[0-9.]+$' | sort --version-sort | tail -n1 | sed 's/v//'
            IMMICH_VERSION: 1.124.0
        cmds:
            - echo -e '\e[44;1m[ Building Immich Server ]\e[0;0m'
            - sed -i '/IMMICH_VERSION=/d' .env
            - echo "IMMICH_VERSION={{.IMMICH_VERSION}}" >> .env
            - git clone -b v{{.IMMICH_VERSION}} {{.IMMICH_SOURCE}} immich
            - sed -r "s,@sha256:[a-f0-9]+,,g;" immich/machine-learning/Dockerfile > Dockerfile.machine-learning
            - sed -r "s,@sha256:[a-f0-9]+,,g;" immich/server/Dockerfile > Dockerfile.server
            - docker compose build --push
            - rm -rf immich Dockerfile.*
            - sed -i '/IMMICH_VERSION=/d' .env
            - echo "[ Done ]"

    checkout:
        silent: true
        vars:
#            IMMICH_VERSION:
#                sh: git ls-remote --tags {{.IMMICH_SOURCE}} 'refs/tags/*' 2>/dev/null | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -E '^v[0-9.]+$' | sort --version-sort | tail -n1 | sed 's/v//'
            IMMICH_VERSION: 1.124.0
        cmds:
            - echo {{.IMMICH_VERSION}}

    default:
        silent: true
        cmds:
            - task -l
