services:

    caddy:
        image: $REGISTRY/$NAME:$POWERSHELL_VERSION
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - REGISTRY
                - POWERSHELL_VERSION
                - POWERSHELL_URL
                - PUID
                - PGID
            tags:
                - $REGISTRY/$NAME:latest
