
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Onedrive Client'
        silent: true
        vars:
            ONEDRIVE_VERSION:
                sh: git ls-remote --tags {{.ONEDRIVE_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo -e '\e[44;1m[ Building Onedrive Client ]\e[0;0m'
            - sed -i '/ONEDRIVE_VERSION=/d' .env
            - echo "ONEDRIVE_VERSION={{.ONEDRIVE_VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/ONEDRIVE_VERSION=/d' .env
            - echo "[ Done ]"

    checkout:
        silent: true
        vars:
            ONEDRIVE_VERSION:
                sh: git ls-remote --tags {{.ONEDRIVE_SOURCE}} 'refs/tags/v*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | sort --version-sort | tail -n1 | sed -r 's/v(.*)/\1/'
        cmds:
            - echo "{{.ONEDRIVE_VERSION}}"

    all:
        desc: 'Build and Synchronize'
        silent: true
        cmds:
            - task: build

    default:
        silent: true
        cmds:
            - task -l
