#!/bin/sh

set -e

INI="locale_ru-RU.ini"

DST="/src/gitea/options/locale/$INI"
MOD="/opt/translate.ini"

echo "Fix translations..."
/opt/fix_locale -in $DST -mod $MOD -out $DST
echo "Translation finished."
