services:

    rust:
        image: $REGISTRY/$NAME:latest
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - REGISTRY
            tags:
                - $SYNC_TARGET/$NAME:latest
