
version: 3

dotenv: [ '.env' ]

tasks:

    build-mariadb:
        silent: true
        internal: true
        vars:
            MARIADB_TAG:
                sh: git ls-remote --refs {{.MARIADB_SOURCE}} 'refs/tags/mariadb-{{.VERSION}}.*' | sed -e '/.*^{}/d; s,.*\/,,; /.*\..*\..*\..*/d' | sort --version-sort | tail -n1
            MARIADB_VERSION:
                sh: echo {{.MARIADB_TAG}} | sed -r 's/mariadb-(.*)/\1/'
        cmds:
            - sed -i '/VERSION=/d; /MARIADB_TAG=/d' .env
            - echo -e "VERSION={{.VERSION}}\nMARIADB_VERSION={{.MARIADB_VERSION}}\nMARIADB_TAG={{.MARIADB_TAG}}" >> .env
            - docker compose build --push
            - sed -i '/VERSION=/d; /MARIADB_TAG=/d' .env
            - echo "[ Done ]"

    build:
        desc: 'Build MariaDB Server'
        silent: true
        cmds:
            - echo -e '\e[44;1m[ Building MariaDB Server ]\e[0;0m'
            - for: { var: MARIADB_VERSION_LIST }
              task: build-mariadb
              vars:
                VERSION: '{{.ITEM}}'

    checkout-mariadb:
        silent: true
        internal: true
        vars:
            MARIADB_TAG:
                sh: git ls-remote --refs {{.MARIADB_SOURCE}} 'refs/tags/mariadb-{{.VERSION}}.*' | sed -e '/.*^{}/d; s,.*\/,,; /.*\..*\..*\..*/d' | sort --version-sort | tail -n1
            MARIADB_VERSION:
                sh: echo {{.MARIADB_TAG}} | sed -r 's/mariadb-(.*)/\1/'
        cmds:
            - echo -n "{{.MARIADB_VERSION}} "

    checkout:
        silent: true
        cmds:
            - for: { var: MARIADB_VERSION_LIST }
              task: checkout-mariadb
              vars:
                VERSION: '{{.ITEM}}'

    all:
        desc: 'Build and Synchronize'
        silent: true
        cmds:
            - task: build

    default:
        silent: true
        cmds:
            - task -l
