
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Yandex.Disk Client'
        silent: true
        cmds:
            - echo -e '\e[44;1m[ Building Yandex.Disk Client ]\e[0;0m'
            - docker compose build --push
            - echo "[ Done ]"

    checkout:
        silent: true
        cmds:
            - echo latest

    all:
        desc: 'Build and Synchronize'
        silent: true
        cmds:
            - task: build

    default:
        silent: true
        cmds:
            - task -l
