services:

    actions:
        image: $REGISTRY/$NAME:alpine
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
            target: actions-alpine
            args:
                - REGISTRY
                - TOOLS_URL
                - TOOLS_LIST
            tags:
                - $REGISTRY/$NAME:latest
                - $SYNC_TARGET/$NAME:alpine
                - $SYNC_TARGET/$NAME:latest
