
version: 3

dotenv: [ '.env' ]

vars:
    TAGS: "alpine"

tasks:

    build-tag:
        silent: true
        internal: true
        cmds:
            - echo "{{.TITLE}}"
            - docker compose build --push {{.TAG}}
            - echo "[ Done ]"

    build:
        desc: 'Build Actions TAG'
        silent: true
        cmds:
            - echo -e '\e[44;1m[ Building Actions TAGS ]\e[0;0m'
            - for: { var: TAGS }
              task: build-tag
              vars:
                TITLE: "- Action TAG [{{.ITEM}}]"
                TAG: '{{.ITEM}}'

    checkout:
        silent: true
        cmds:
            - echo latest

    default:
        silent: true
        cmds:
            - task -l
