services:

    minio:
        image: $REGISTRY/$NAME:latest
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - REGISTRY
                - MINIO_SOURCE
                - MINIO_VERSION
                - PUID
                - PGID
            tags:
                - $SYNC_TARGET/$NAME:latest
                - $SYNC_TARGET/$NAME:$MINIO_VERSION
