
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Minio S3 Server'
        silent: true
        vars:
            MINIO_VERSION:
                sh: git ls-remote --tags {{.MINIO_SOURCE}} 'refs/tags/RELEASE.*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | sort --version-sort | tail -n1
        cmds:
            - echo -e '\e[44;1m[ Building Minio S3 Server ]\e[0;0m'
            - sed -i '/MINIO_VERSION=/d' .env
            - echo "MINIO_VERSION={{.MINIO_VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/MINIO_VERSION=/d' .env
            - echo "[ Done ]"

    checkout:
        silent: true
        vars:
            MINIO_VERSION:
                sh: git ls-remote --tags {{.MINIO_SOURCE}} 'refs/tags/RELEASE.*' | sed -e '/.*^{}/d' -e 's,.*\/,,' | grep -v 'rc' | sort --version-sort | tail -n1
        cmds:
            - echo {{.MINIO_VERSION}}

    all:
        desc: 'Build and Synchronize'
        silent: true
        cmds:
            - task: build

    default:
        silent: true
        cmds:
            - task -l
