
version: 3

dotenv: [ '.env' ]

tasks:

    build:
        desc: 'Build Apache Web Server'
        silent: true
        cmds:
            - echo -e '\e[44;1m[ Building Apache Web Server ]\e[0;0m'
            - docker compose build --push
            - echo "[ Done ]"

    checkout:
        silent: true
        cmds:
            - echo latest

    default:
        silent: true
        cmds:
            - task -l
