
version: 3

dotenv: [ '.env' ]

tasks:

    build-postgres:
        silent: true
        internal: true
        vars:
            POSTGRES_VERSION:
                sh: git ls-remote --refs {{.POSTGRES_SOURCE}} 'refs/tags/REL_{{.VERSION}}_*' | sed 's,.*\/,,; s,\^{},,;' | grep -Ev 'RC|BETA' | sed -r 's/^REL_(.*)/\1/' | tr '_' '.' | sort --version-sort | tail -n1
            POSTGRES_TAG:
                sh: echo "REL_{{.POSTGRES_VERSION}}" | tr '.' '_'
            PG_VECTOR_VERSION:
                sh: git ls-remote --refs {{.PG_VECTOR_SOURCE}} 'refs/tags/v*' | sed 's,.*\/,,; s,\^{},,;' | sed -r 's/v(.*)/\1/' | sort --version-sort | tail -n1
        cmds:
            - echo "- {{.TITLE}} ({{.POSTGRES_VERSION}})"
            - sed -i '/POSTGRES_VERSION=/d; /POSTGRES_TAG=/d; /MAJOR_VERSION=/d; /PG_VECTOR_VERSION=/d' .env
            - echo -e "POSTGRES_VERSION={{.POSTGRES_VERSION}}\nPOSTGRES_TAG={{.POSTGRES_TAG}}\nMAJOR_VERSION={{.VERSION}}\nPG_VECTOR_VERSION={{.PG_VECTOR_VERSION}}" >> .env
            - docker compose build --push
            - sed -i '/POSTGRES_VERSION=/d; /POSTGRES_TAG=/d; /MAJOR_VERSION=/d; /PG_VECTOR_VERSION=/d' .env
            - echo "[ Done ]"

    build:
        desc: 'Build Alt Linux'
        silent: true
        cmds:
            - echo -e '\e[44;1m[ Building Postgres ]\e[0;0m'
            - for: { var: POSTGRES_VERSION_LIST }
              task: build-postgres
              vars:
                TITLE: 'Postgres {{.ITEM}}'
                VERSION: '{{.ITEM}}'

    checkout-postgres:
        silent: true
        internal: true
        vars:
            POSTGRES_VERSION:
                sh: git ls-remote --refs {{.POSTGRES_SOURCE}} 'refs/tags/REL_{{.VERSION}}_*' | sed 's,.*\/,,; s,\^{},,;' | grep -Ev 'RC|BETA' | sed -r 's/^REL_(.*)/\1/' | tr '_' '.' | sort --version-sort | tail -n1
        cmds:
            - echo -n "{{.POSTGRES_VERSION}} "

    checkout:
        silent: true
        cmds:
            - for: { var: POSTGRES_VERSION_LIST }
              task: checkout-postgres
              vars:
                VERSION: '{{.ITEM}}'

    all:
        desc: 'Build and Synchronize'
        silent: true
        cmds:
            - task: build

    default:
        silent: true
        cmds:
            - task -l
