services:

    php:
        image: $REGISTRY/$NAME:$PHP_VERSION
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
            target: $PHP_TARGET
            args:
                - REGISTRY
                - ALPINE_VERSION
                - PHP_NUM
                - PHP_VERSION
                - PHP_MODULES
                - PECL_MODULES
                - PUID
                - PGID
            tags:
                - $REGISTRY/$NAME:latest
                - $SYNC_TARGET/$NAME:$PHP_VERSION
                - $SYNC_TARGET/$NAME:latest
