
version: 3

dotenv: [ '.env' ]

tasks:

    build-alt:
        silent: true
        internal: true
        vars:
            ALT_SOURCE_URL: "{{.ALT_URL}}/p{{.VERSION}}/{{.ALT_ARCH}}/alt-p{{.VERSION}}-{{.ALT_ARCH}}.tar.xz"
            ALT_SOURCE: "alt-p{{.VERSION}}-{{.ALT_ARCH}}.tar.xz"
        cmds:
            - echo "- {{.TITLE}}"
            - wget -q --show-progress {{.ALT_SOURCE_URL}}
            - sed -i '/ALT_VERSION=/d' .env
            - echo "ALT_VERSION={{.VERSION}}" >> .env
            - docker compose build --push --build-arg ALT_SOURCE={{.ALT_SOURCE}}
            - sed -i '/ALT_VERSION=/d' .env
            - rm -f {{.ALT_SOURCE}}
            - echo "[ Done ]"

    build:
        desc: 'Build Alt Linux'
        silent: true
        cmds:
            - echo -e '\e[44;1m[ Building Alt Linux ]\e[0;0m'
            - for: { var: ALT_VERSION_LIST }
              task: build-alt
              vars:
                TITLE: 'Alt Linux {{.ITEM}}'
                VERSION: '{{.ITEM}}'

    sync-alt:
        silent: true
        internal: true
        cmds:
            - echo "Sync {{.REGISTRY}}/{{.NAME}}:{{.VERSION}} => {{.SYNC_TARGET}}/{{.NAME}}:{{.VERSION}}"
            - skopeo copy docker://{{.REGISTRY}}/{{.NAME}}:{{.VERSION}} docker://{{.SYNC_TARGET}}/{{.NAME}}:{{.VERSION}}
            - echo "Sync {{.REGISTRY}}/{{.NAME}}:latest => {{.SYNC_TARGET}}/{{.NAME}}:latest"
            - skopeo copy docker://{{.REGISTRY}}/{{.NAME}}:latest docker://{{.SYNC_TARGET}}/{{.NAME}}:latest
            - echo "[ Done ]"

    sync:
        desc: 'Synchronize with DockerHub'
        silent: true
        cmds:
            - echo -e '\e[44;1m[ Synchronize with DockerHub ]\e[0;0m'
            - for: { var: ALT_VERSION_LIST }
              task: sync-alt
              vars:
                VERSION: '{{.ITEM}}'

    checkout:
        silent: true
        cmds:
            - echo "{{.ALT_VERSION_LIST}}"

    all:
        desc: 'Build and Synchronize'
        silent: true
        cmds:
            - task: build
            - task: sync

    default:
        silent: true
        cmds:
            - task -l
